# name: Deploy React App to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Build React app
#         run: npm run build 

#       - name: Deploy to EC2
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           source: dist/*     
#           target: /home/ubuntu/react-ci-cd-demo
#           port: 22

name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd /home/ubuntu/react-ci-cd-demo
            
            # Pull latest changes from GitHub
            git pull origin main
            
            # Install dependencies
            npm ci
            
            # Build the application
            npm run build
            
            # Deploy to nginx
            sudo rm -rf /var/www/react-app/*
            sudo cp -r dist/* /var/www/react-app/
            
            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/react-app
            sudo chmod -R 755 /var/www/react-app
            
            # Reload nginx
            sudo systemctl reload nginx
            
            echo "Deployment completed successfully!"
            echo "Files deployed at $(date):"
            ls -la /var/www/react-app/